name: Test Action-to-Action Cross-Repo References

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (needed to use local actions)
        uses: actions/checkout@v4

      - name: Run wrapped hello-local
        uses: ./.github/actions/wrapped-hello-local

      - name: Run wrapped hello-root
        uses: ./.github/actions/wrapped-hello-root
